# Generated by Django 4.2 on 2023-08-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FashionPlace', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FashionPlace.profile'),
        ),
    ]
